### ISSUE TITLE
Add filters in search feature

### ISSUE THREAD

**Issue by lokified** [lokified/Plitso#3]
- currently filters by name/title, instructions, ingredients and country in [RecipeDetailDao](https://github.com/lokified/Plitso/blob/master/app/src/main/java/com/loki/plitso/data/local/dao/RecipeDetailDao.kt). change to filter by name, country and ingredients. 

- Ui should have user select what to filter -  use checkboxes

**Comment by pesta007** [comment]
Could you elaborate more? Should the user be presented with a section where they can select filters, such as name, country, or ingredients, using checkboxes when they open the search screen? Or do you expect them to have both options—selecting filters via checkboxes and typing search queries?

**Comment by pesta007** [comment]
Are you describing something like this:
```
    fun searchRecipe(name: String, country: String, ingredients: String): Flow<List<RecipeDetail>>
```
do you have a figma design of the desired new UI?

**Comment by lokified** [comment]
I have been working on this.  It has both options, selecting filters in checkboxes and also search queries.

Below is the screenshot how i implemented it. 
You can find in the branch [ft_search_filter](https://github.com/lokified/Plitso/tree/ft_search_filter)


<img src="https://github.com/user-attachments/assets/a4e859f2-4214-4ae7-99f2-30ed5036d1d8" height="30%" width = "30%" >
